# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e684e07dda51c0ccc4b2d03d78ce8eec31d40806fe204e13456ce940c71db7c198e5dfa9898737c96b6dfd95ebae2bb66d92c35fe3bb6af663c2cf523047bbf3

test:
  secret_key_base: 1cfac96641aa621f86cf3cb053e8b635777394ad0b6c07d76df44ea0ce0fddaea6d7853018de3938a32e47ceb5c2b337320066153337af40833bebf5f8a071bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
